In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn 
import pandas as pd
import os, gc, sys, time
import tensorflow as tf
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn')
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

## **2.1数据集titanic**

In [2]:
train_file = './data/titanic/titanic_train.csv'
eval_file = './data/titanic/titanic_eval.csv'

train_df = pd.read_csv(train_file)
eval_df = pd.read_csv(eval_file)

train_df.head(5)

,survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,0,male,22.0,1,0,7.2500,Third,unknown,Southampton,n
1,1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
2,1,female,26.0,0,0,7.9250,Third,unknown,Southampton,y
3,1,female,35.0,1,0,53.1000,First,C,Southampton,n
4,0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y

In [3]:
y_train = train_df.pop('survived')
y_eval = eval_df.pop('survived')

train_df.head(10)

,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.2500,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
2,female,26.0,0,0,7.9250,Third,unknown,Southampton,y
3,female,35.0,1,0,53.1000,First,C,Southampton,n
4,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y
5,male,2.0,3,1,21.0750,Third,unknown,Southampton,n
6,female,27.0,0,2,11.1333,Third,unknown,Southampton,n
7,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n
8,female,4.0,1,1,16.7000,Third,G,Southampton,n
9,male,20.0,0,0,8.0500,Third,unknown,Southampton,y

## **2.2 feature_column的使用**
**离散特征**: one-hot编码     
**连续特征**: 分桶

In [4]:
categorical_columns = ['sex', 'n_siblings_spouses', 'parch', 'class',
                       'deck', 'embark_town', 'alone']
numeric_columns = ['age', 'fare']

feature_columns = []

# 将类别特征转换为one-hot的特征
for categorical_column in categorical_columns:
    vocab = train_df[categorical_column].unique()
    # 使用tf.feature_columns下的api
    feature_columns.append(tf.feature_column.indicator_column(tf.feature_column.categorical_column_with_vocabulary_list(categorical_column, vocab)))
for categorical_column in numeric_columns:
    feature_columns.append(tf.feature_column.numeric_column(categorical_column, dtype=tf.float32))

In [5]:
def make_dataset(data_df, label_df, epochs = 10, shuffle = True, batch_size = 32):
    dataset = tf.data.Dataset.from_tensor_slices((dict(data_df), label_df))
    if shuffle:
        dataset.shuffle(10000)
    dataset = dataset.repeat(epochs).batch(batch_size)
    return dataset

## **1.3  tf自带estimator**

有两种训练的模式
- 直接调用fit的方法
- 将model转换为estimator，然后再进行训练

In [11]:
output_dir = 'linear_model'
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

linear_estimator = tf.estimator.LinearClassifier(model_dir=output_dir, 
                                                     n_classes = 2,
                                                   feature_columns=feature_columns)
linear_estimator.train(input_fn = lambda : make_dataset(train_df, y_train, epochs=100))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'linear_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x00000287B6924D30>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into linear_model\model.ckpt.
INFO:tensorflow:loss = 0.6931472, step = 0
INFO:tensorflow:global_step/sec: 158.651
INFO:tensorflow:loss = 0.44970068, step = 100 (0.630 sec)
INFO:tensorflow:global_step/sec: 211.241
INFO:tensorflow:loss = 0.6174818, step = 200 (0.474 sec)
INFO:tensorflow:global_step/sec: 205.888
INFO:tensorflow:loss = 0.44734153, step = 300 (0.486 sec)
INFO:tensorflow:global_step/sec: 206.728
INFO:tensorflow:loss = 0.39295372, step = 400 (0.484 sec)
INFO:tensorflow:global_step/sec: 209.327
INFO:tensorflow:loss = 0.435954, step = 500 (0.478 sec)
INFO:tensorflow:global_step/sec: 186.725
INFO:tensorflow:loss = 0.5305938, step = 600 (0.537 sec)
INFO:tensorflow:global_step/sec: 209.326
INFO:tensorflow:loss = 0.46564862, step = 700 (0.477 sec)
INFO:tensorflow:global_step/sec: 203.795
INFO:tensorflow:loss = 0.38957122, step = 800 (0.490 sec)
INFO:tensorflow:global_step/sec: 190.623
INFO:tensorflow:loss = 0.2330541, step = 900 (0.526 sec)
INFO:tensorflow:global_step/sec: 164.372
INFO:tensorflow:loss = 0.42467216, step = 1000 (0.609 sec)
INFO:tensorflow:global_step/sec: 186.025
INFO:tensorflow:loss = 0.42120147, step = 1100 (0.537 sec)
INFO:tensorflow:global_step/sec: 195.049
INFO:tensorflow:loss = 0.3718462, step = 1200 (0.513 sec)
INFO:tensorflow:global_step/sec: 190.261
INFO:tensorflow:loss = 0.31621695, step = 1300 (0.526 sec)
INFO:tensorflow:global_step/sec: 199.736
INFO:tensorflow:loss = 0.52608705, step = 1400 (0.501 sec)
INFO:tensorflow:global_step/sec: 205.466
INFO:tensorflow:loss = 0.5543226, step = 1500 (0.487 sec)
INFO:tensorflow:global_step/sec: 211.982
INFO:tensorflow:loss = 0.34366047, step = 1600 (0.472 sec)
INFO:tensorflow:global_step/sec: 204.141
INFO:tensorflow:loss = 0.37184173, step = 1700 (0.489 sec)
INFO:tensorflow:global_step/sec: 211.981
INFO:tensorflow:loss = 0.3996112, step = 1800 (0.473 sec)
INFO:tensorflow:global_step/sec: 205.046
INFO:tensorflow:loss = 0.31126377, step = 1900 (0.488 sec)
INFO:tensorflow:Saving checkpoints for 1960 into linear_model\model.ckpt.
INFO:tensorflow:Loss for final step: 0.29502285.

In [12]:
linear_estimator.evaluate(input_fn = lambda : make_dataset(
    eval_df, y_eval, epochs = 1, shuffle = False))

INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer linear/linear_model is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-12-25T13:47:02Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from linear_model\model.ckpt-1960
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-12-25-13:47:03
INFO:tensorflow:Saving dict for global step 1960: accuracy = 0.780303, accuracy_baseline = 0.625, auc = 0.8393022, auc_precision_recall = 0.78339857, average_loss = 0.4715886, global_step = 1960, label/mean = 0.375, loss = 0.45434365, precision = 0.7113402, prediction/mean = 0.3666899, recall = 0.6969697
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1960: linear_model\model.ckpt-1960

{'accuracy': 0.780303,
 'accuracy_baseline': 0.625,
 'auc': 0.8393022,
 'auc_precision_recall': 0.78339857,
 'average_loss': 0.4715886,
 'label/mean': 0.375,
 'loss': 0.45434365,
 'precision': 0.7113402,
 'prediction/mean': 0.3666899,
 'recall': 0.6969697,
 'global_step': 1960}

In [16]:
output_dir = 'dnn_model'
if not os.path.exists(output_dir):
    os.mkdir(output_dir)

dnn_estimator = tf.estimator.DNNClassifier(model_dir=output_dir, 
                                           n_classes = 2,
                                           hidden_units=[128, 128],
                                           activation_fn=tf.nn.relu,
                                           optimizer='Adam',
                                           feature_columns=feature_columns)
dnn_estimator.train(input_fn = lambda : make_dataset(train_df, y_train, epochs=100))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'dnn_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000002891A1DD8D0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer dnn is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into dnn_model\model.ckpt.
INFO:tensorflow:loss = 1.9219396, step = 0
INFO:tensorflow:global_step/sec: 151.462
INFO:tensorflow:loss = 0.55637336, step = 100 (0.661 sec)
INFO:tensorflow:global_step/sec: 187.36
INFO:tensorflow:loss = 0.5889189, step = 200 (0.534 sec)
INFO:tensorflow:global_step/sec: 178.174
INFO:tensorflow:loss = 0.49012503, step = 300 (0.561 sec)
INFO:tensorflow:global_step/sec: 182.062
INFO:tensorflow:loss = 0.43932256, step = 400 (0.550 sec)
INFO:tensorflow:global_step/sec: 176.519
INFO:tensorflow:loss = 0.39585114, step = 500 (0.566 sec)
INFO:tensorflow:global_step/sec: 180.041
INFO:tensorflow:loss = 0.5267688, step = 600 (0.555 sec)
INFO:tensorflow:global_step/sec: 176.168
INFO:tensorflow:loss = 0.4352638, step = 700 (0.569 sec)
INFO:tensorflow:global_step/sec: 179.23
INFO:tensorflow:loss = 0.29690534, step = 800 (0.557 sec)
INFO:tensorflow:global_step/sec: 182.272
INFO:tensorflow:loss = 0.19088838, step = 900 (0.550 sec)
INFO:tensorflow:global_step/sec: 158.473
INFO:tensorflow:loss = 0.6028949, step = 1000 (0.631 sec)
INFO:tensorflow:global_step/sec: 178.174
INFO:tensorflow:loss = 0.7849407, step = 1100 (0.561 sec)
INFO:tensorflow:global_step/sec: 175.84
INFO:tensorflow:loss = 0.34497297, step = 1200 (0.568 sec)
INFO:tensorflow:global_step/sec: 174.769
INFO:tensorflow:loss = 0.23608357, step = 1300 (0.573 sec)
INFO:tensorflow:global_step/sec: 154.182
INFO:tensorflow:loss = 0.41674083, step = 1400 (0.648 sec)
INFO:tensorflow:global_step/sec: 156.447
INFO:tensorflow:loss = 0.39198762, step = 1500 (0.638 sec)
INFO:tensorflow:global_step/sec: 173.716
INFO:tensorflow:loss = 0.30716348, step = 1600 (0.578 sec)
INFO:tensorflow:global_step/sec: 167.337
INFO:tensorflow:loss = 0.3897701, step = 1700 (0.597 sec)
INFO:tensorflow:global_step/sec: 179.209
INFO:tensorflow:loss = 0.22921512, step = 1800 (0.558 sec)
INFO:tensorflow:global_step/sec: 176.539
INFO:tensorflow:loss = 0.20322767, step = 1900 (0.569 sec)
INFO:tensorflow:Saving checkpoints for 1960 into dnn_model\model.ckpt.
INFO:tensorflow:Loss for final step: 0.2576739.

In [17]:
dnn_estimator.evaluate(input_fn = lambda : make_dataset(
    eval_df, y_eval, epochs = 1, shuffle = False))

INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:Layer dnn is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-12-25T13:50:46Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from dnn_model\model.ckpt-1960
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Finished evaluation at 2019-12-25-13:50:47
INFO:tensorflow:Saving dict for global step 1960: accuracy = 0.780303, accuracy_baseline = 0.625, auc = 0.83936334, auc_precision_recall = 0.81086457, average_loss = 0.528422, global_step = 1960, label/mean = 0.375, loss = 0.5109839, precision = 0.6722689, prediction/mean = 0.47925717, recall = 0.8080808
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1960: dnn_model\model.ckpt-1960

{'accuracy': 0.780303,
 'accuracy_baseline': 0.625,
 'auc': 0.83936334,
 'auc_precision_recall': 0.81086457,
 'average_loss': 0.528422,
 'label/mean': 0.375,
 'loss': 0.5109839,
 'precision': 0.6722689,
 'prediction/mean': 0.47925717,
 'recall': 0.8080808,
 'global_step': 1960}

estimator在model之外额外完成了很多操作，或保存tensorboard和model